{% set version = "0.9.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcppclassic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppClassic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppClassic/RcppClassic_{{ version }}.tar.gz
  sha256: 72afd1bec5a488c7cc4fdb7728d006cf83bbb3f53223e18c320ee3024f4e76a2

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.10.2
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.10.2

test:
  commands:
    - $R -e "library('RcppClassic')"           # [not win]
    - "\"%R%\" -e \"library('RcppClassic')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RcppClassic
  license: GPL-2.0-or-later
  summary: The 'RcppClassic' package provides a deprecated C++ library which facilitates the integration of R and C++. New projects should use the new 'Rcpp' 'API' in the 'Rcpp' package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RcppClassic
# Title: Deprecated 'classic' 'Rcpp' 'API'
# Version: 0.9.12
# Date: 2019-12-08
# Author: Dirk Eddelbuettel and Romain Francois, with contributions by David Reiss, and based on code written during 2005 and 2006 by Dominick Samperi
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Description: The 'RcppClassic' package provides a deprecated C++ library which facilitates the integration of R and C++. New projects should use the new 'Rcpp' 'API' in the 'Rcpp' package.
# Depends: R (>= 2.12.0)
# Imports: Rcpp (>= 0.10.2), methods
# Suggests: tinytest
# LinkingTo: Rcpp
# License: GPL (>= 2)
# MailingList: Please send questions and comments about Rcpp to rcpp-devel@lists.r-forge.r-project.org
# BugReports: https://github.com/eddelbuettel/rcppclassic/issues
# NeedsCompilation: yes
# Packaged: 2019-12-08 23:19:32.781457 UTC; edd
# Repository: CRAN
# Date/Publication: 2019-12-09 06:40:29 UTC
