appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Tg8oZYCOpb2ep4E24+VCQ+Xxken1gKWeP7IOONrBncXcuoCUj9fWnxX73aCUegcodLHRrDPi+X8PPHDFX2TZflrTpyRKWb5+ebm03UkSN5ODt4bm1uwA8wlO1KbZDDJg+BwaI/iQuuIPzLK//HAfFCyfs4nCW5u75YQaTO0fuRYAtQjcu6ztWdpD/WiQgQWFrqY/EL9gOyV6VYSR5vaSWp+uqqKfLf21P+H2G21rbSd4amnQ+PUgcFd/GgqZYqSSEWv9CWapRHpLX9SHQGTiJk382kimEOScIRJf7ZUdBCoWyG3QmBu0WX8R93K//hjGibPn4KmOsOYsfshiwCIV4Qr9ZgMX6gfMQxeLhwzzMwp9Ac1P57rLsLr7LDEa5pW0vKoAjRACHMtnJXaAx/rKOgXVBNLe6R9aMA/jWt6/bThAUigKOUt9lrXvmQODL/Qub1/vZBjPQM7tEXucRTg6UkXY3J7sLu+zen4aUsKQvtvCfDEy6GQdVVpgZ434d86m57vyXloYyVC5AimQPBLE1hzUu/evLCCTNkjVZFq9jdIB6g+C3tClfhi66hId7tKCgQP/EyXhLqVdOZfkVfFxFUkwbH8wuWrt2kAJV+ODimj/3GLKj3eOBk3q8g+02Nh0MWAtHilRnSn3uiRd5HHjar3Y6iRUXeYFJA2HIZWK8EI=}
